namespace ArtFactory.Domain
{
  public enum JobStatus
  {
    /// <summary>
    /// The job is queued for execution.
    /// </summary>
    Waiting = 1,

    /// <summary>
    /// The job is processing.
    /// </summary>
    InProgress = 2,

    /// <summary>
    /// The job has completed successfully
    /// </summary>
    Completed = 3,

    /// <summary>
    /// The job failed, check the messages for reasons.
    /// </summary>
    Failed = 4,

    /// <summary>
    /// the job is attempting to abort gracefully.
    /// </summary>
    Aborting = 5,

    /// <summary>
    /// The job has aborted.
    /// </summary>
    Aborted = 6,

    /// <summary>
    /// The artifacts generated by the job's execution
    /// have been written to their output destinations.
    /// </summary>
    Deployed = 7,

    /// <summary>
    /// The job has paused to allow higher priority jobs to process.
    /// </summary>
    Suspended = 8
  }
}